Tang dev
ScafTeam/scaf-frontend pull request #5
Opened 2022-11-29 14:11 UTC by ChrisTangzz

我完成創建刪除 專案、repo

2022-11-29 17:09 UTC, jimmyhealer commented on src/components/Global.vue
> +<script lang="ts" setup>
應刪除未使用的vue

2022-11-29 17:19 UTC, jimmyhealer requested changes

2022-11-29 17:19 UTC, jimmyhealer commented on src/views/AuthView.vue
> +const src = "src\\Logo.png";
使用 "src/Logo.png" 為佳

2022-11-29 17:19 UTC, jimmyhealer commented on src/views/ProjectSettingView.vue
> +  /*�ŧi���u�ʧG������*/
?

2022-11-29 17:19 UTC, jimmyhealer commented on src/views/SettingsView.vue
> +      <!-- �W��func���g -->
?

2022-11-29 17:19 UTC, jimmyhealer commented on src/views/SettingsView.vue
> +      <!-- �H�U��click func���g -->
?

2022-11-29 17:19 UTC, jimmyhealer commented on src/views/ProjectsView.vue
> +  console.log("chose");
console.log 註解

2022-11-29 17:19 UTC, jimmyhealer commented on src/views/ProjectsView.vue
> +  console.log("zz");
console.log 註解

2022-11-29 17:19 UTC, jimmyhealer commented on src/views/ProjectSettingView.vue
> +          <p v-for="o in 4" :key="o" class="setting-members-item">
why " o in 4" ?

2022-11-29 17:19 UTC, jimmyhealer commented on src/components/navbar.vue
> +const src = "src\\Logo.png";
用 "src/Logo.png" 為佳。

2022-11-29 17:21 UTC, jimmyhealer commented
@0-ch 改一下

2022-11-30 04:20 UTC, 0-ch commented on src/components/Global.vue
> +<script lang="ts" setup>
刪了

2022-11-30 04:20 UTC, 0-ch commented on src/views/AuthView.vue
> +const src = "src\\Logo.png";
改了

2022-11-30 04:22 UTC, 0-ch commented on src/views/ProjectSettingView.vue
> +  /*�ŧi���u�ʧG������*/
中文功能註解 我刪掉

2022-11-30 04:23 UTC, 0-ch commented on src/views/SettingsView.vue
> +      <!-- �W��func���g -->
原為 <!-- 上傳func未寫 --> 我刪掉

2022-11-30 04:24 UTC, 0-ch commented on src/views/SettingsView.vue
> +      <!-- �H�U��click func���g -->
原為 <!-- 以下兩click func未寫 --> 我刪掉

2022-11-30 04:26 UTC, 0-ch commented on src/components/navbar.vue
> +const src = "src\\Logo.png";
改了

2022-11-30 04:26 UTC, 0-ch commented on src/views/ProjectDocView.vue
> +  /*�ŧi���u�ʧG������*/
中文功能註解 我刪掉

2022-11-30 04:28 UTC, 0-ch commented on src/views/ProjectSettingView.vue
> +          <p v-for="o in 4" :key="o" class="setting-members-item">
具體物件沒寫 所以就隨便列四項

2022-11-30 04:40 UTC, jimmyhealer approved these changes

2022-11-30 04:45 UTC, merged